[app_servers]
10.0.11.169 ansible_user=ubuntu ansible_ssh_private_key_file=~/Downloads/PRTKEY.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/Downloads/PRTKEY.pem ubuntu@44.213.178.254" -o StrictHostKeyChecking=no'
10.0.12.211 ansible_user=ubuntu ansible_ssh_private_key_file=~/Downloads/PRTKEY.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/Downloads/PRTKEY.pem ubuntu@44.213.178.254" -o StrictHostKeyChecking=no'
